[package]
name = "stormbuffer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
build = "build.rs"
default-run = "sbuf"
autobins = false

[[bin]]
name = "sbuf"
path = "src/bin/sbuf.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
owo-colors.workspace = true
serde_json.workspace = true
stormbuffer-core = { package = "stormbuffer-core", version = "=0.1.0", path = "../core" }
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[build-dependencies]
clap.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true
