[package]
name = "stormbuffer-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
publish = false

[[bin]]
name = "stormbuffer-server"
path = "src/main.rs"

[dependencies]
stormbuffer-core = { package = "stormbuffer-core", version = "=0.1.0", path = "../core" }
